Test for -lposix4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2784,6 +2784,77 @@ else
    ooc_have_lib_rt=FALSE
 fi
 
+
+echo "$as_me:$LINENO: checking for sem_init in -lposix4" >&5
+echo $ECHO_N "checking for sem_init in -lposix4... $ECHO_C" >&6
+if test "${ac_cv_lib_posix4_sem_init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lposix4  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char sem_init ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+sem_init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_posix4_sem_init=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_posix4_sem_init=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_posix4_sem_init" >&5
+echo "${ECHO_T}$ac_cv_lib_posix4_sem_init" >&6
+if test $ac_cv_lib_posix4_sem_init = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBPOSIX4 1
+_ACEOF
+
+  LIBS="-lposix4 $LIBS"
+
+fi
+
+if test "$ac_cv_lib_posix4_sem_init" = yes; then
+   ooc_have_lib_posix4=TRUE
+else
+   ooc_have_lib_posix4=FALSE
+fi
+
 if test $TARGET_OS = Win32; then
   ooc_have_lib_m=FALSE
 
@@ -5587,6 +5658,7 @@ s,@ooc_have_lib_pthread@,$ooc_have_lib_pthread,;t t
 s,@ooc_have_lib_gc@,$ooc_have_lib_gc,;t t
 s,@ooc_have_lib_xnet@,$ooc_have_lib_xnet,;t t
 s,@ooc_have_lib_rt@,$ooc_have_lib_rt,;t t
+s,@ooc_have_lib_posix4@,$ooc_have_lib_posix4,;t t
 s,@ooc_have_lib_mingwex@,$ooc_have_lib_mingwex,;t t
 s,@ooc_have_lib_wsock32@,$ooc_have_lib_wsock32,;t t
 s,@ooc_have_lib_m@,$ooc_have_lib_m,;t t
