(OS:Files): Add function `MTime' to get the modification time of a file.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4390,6 +4390,62 @@ if test $ooc_target_address = 64; then
   ooc_target_address_type="hugeint"
 fi
 
+echo "$as_me:$LINENO: checking for struct stat.st_mtime_usec" >&5
+echo $ECHO_N "checking for struct stat.st_mtime_usec... $ECHO_C" >&6
+if test "${ac_cv_member_struct_stat_st_mtime_usec+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <sys/stat.h>
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+static struct stat ac_aggr;
+if (ac_aggr.st_mtime_usec)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_member_struct_stat_st_mtime_usec=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_member_struct_stat_st_mtime_usec=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_member_struct_stat_st_mtime_usec" >&5
+echo "${ECHO_T}$ac_cv_member_struct_stat_st_mtime_usec" >&6
+if test $ac_cv_member_struct_stat_st_mtime_usec = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_STRUCT_STAT_USEC 1
+_ACEOF
+
+fi
+
 
 
 echo "$as_me:$LINENO: checking return type of signal handlers" >&5
