missed rebuild

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1235,7 +1235,7 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-ac_config_files="$ac_config_files ENV rsrc/OOC/Makefile.config rsrc/OOC/TestFramework/config.xml rsrc/OOC/xml/config.sh"
+ac_config_files="$ac_config_files ENV rsrc/OOC/Makefile.config rsrc/OOC/TestFramework/config.xml"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -1571,8 +1571,7 @@ do
   "ENV" ) CONFIG_FILES="$CONFIG_FILES ENV" ;;
   "rsrc/OOC/Makefile.config" ) CONFIG_FILES="$CONFIG_FILES rsrc/OOC/Makefile.config" ;;
   "rsrc/OOC/TestFramework/config.xml" ) CONFIG_FILES="$CONFIG_FILES rsrc/OOC/TestFramework/config.xml" ;;
-  "rsrc/OOC/xml/config.sh" ) CONFIG_FILES="$CONFIG_FILES rsrc/OOC/xml/config.sh" ;;
-  *) { { echo "$as_me:1575: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1574: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1776,7 +1775,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1779: creating $ac_file" >&5
+    { echo "$as_me:1778: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1794,7 +1793,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1797: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1796: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1807,7 +1806,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1810: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1809: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
