add check for -lxnet for Solaris systems

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2382,6 +2382,71 @@ _ACEOF
 fi
 
 
+echo "$as_me:$LINENO: checking for socket in -lxnet" >&5
+echo $ECHO_N "checking for socket in -lxnet... $ECHO_C" >&6
+if test "${ac_cv_lib_xnet_socket+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lxnet  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char socket ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+socket ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_xnet_socket=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_xnet_socket=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_xnet_socket" >&5
+echo "${ECHO_T}$ac_cv_lib_xnet_socket" >&6
+if test $ac_cv_lib_xnet_socket = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBXNET 1
+_ACEOF
+
+  LIBS="-lxnet $LIBS"
+
+fi
+
+
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -3933,7 +3998,7 @@ done
 
 
 
-ac_config_files="$ac_config_files ENV rsrc/OOC/Makefile.config rsrc/OOC/oo2crc.xml src/OOC/Config/Autoconf.Mod rsrc/OOC/TestFramework/config.xml"
+ac_config_files="$ac_config_files ENV Makefile.config rsrc/OOC/oo2crc.xml src/OOC/Config/Autoconf.Mod rsrc/OOC/TestFramework/config.xml"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -4407,7 +4472,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "ENV" ) CONFIG_FILES="$CONFIG_FILES ENV" ;;
-  "rsrc/OOC/Makefile.config" ) CONFIG_FILES="$CONFIG_FILES rsrc/OOC/Makefile.config" ;;
+  "Makefile.config" ) CONFIG_FILES="$CONFIG_FILES Makefile.config" ;;
   "rsrc/OOC/oo2crc.xml" ) CONFIG_FILES="$CONFIG_FILES rsrc/OOC/oo2crc.xml" ;;
   "src/OOC/Config/Autoconf.Mod" ) CONFIG_FILES="$CONFIG_FILES src/OOC/Config/Autoconf.Mod" ;;
   "rsrc/OOC/TestFramework/config.xml" ) CONFIG_FILES="$CONFIG_FILES rsrc/OOC/TestFramework/config.xml" ;;
